### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by szymonrychu** [philschatz/atom-pull-requests#17]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [pull-requests](https://github.com/philschatz/atom-pull-requests) package, v0.0.23

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/szymonri/.atom/packages/pull-requests/lib/tree-view-decorator.coffee:98

TypeError: Cannot read property '0' of undefined
    at TreeViewDecorator.module.exports.TreeViewDecorator.markTreeFiles (/Users/szymonri/.atom/packages/pull-requests/lib/tree-view-decorator.coffee:98:44)
    at TreeViewDecorator.module.exports.TreeViewDecorator.updateTreeView (/Users/szymonri/.atom/packages/pull-requests/lib/tree-view-decorator.coffee:86:6)
    at /Users/szymonri/.atom/packages/pull-requests/lib/tree-view-decorator.coffee:43:41
    at Function.module.exports.Emitter.simpleDispatch (/Users/szymonri/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/szymonri/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at GitHubClient.module.exports.GitHubClient._tick (/Users/szymonri/.atom/packages/pull-requests/lib/gh-client.coffee:190:16)
    at /Users/szymonri/.atom/packages/pull-requests/lib/gh-client.coffee:44:28
    at Function.module.exports.Emitter.simpleDispatch (/Users/szymonri/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/szymonri/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Polling.module.exports.Polling.poll (/Users/szymonri/.atom/packages/pull-requests/lib/polling.coffee:11:14)
```

### Commands

```
     -1:32.4.0 platformio-ide:initialize-new-project (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-atom-material-syntax.theme-material-ui)
     -0:15.2.0 build:refresh-targets (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-atom-material-syntax.theme-material-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.0
aligner-python, v1.0.1
atom-alignment, v0.12.1
atom-jinja2, v0.5.0
atom-material-syntax, v0.4.6
atom-slack-snippets, v0.2.0
autocomplete-bash-builtins, v0.3.4
autocomplete-clang, v0.9.4
autocomplete-python, v1.8.1
build, v0.65.0
busy, v0.5.0
file-icons, v1.7.16
fonts, v1.5.0
github-utils, v1.5.0
highlight-column, v0.5.1
highlight-line, v0.11.1
highlight-selected, v0.11.2
language-ini, v1.16.0
language-pgsql, v0.2.3
language-salt, v0.4.0
language-terraform, v0.7.4
linter, v1.11.14
linter-gcc, v0.6.14
material-ui, v1.0.9
merge-conflicts, v1.4.4
minimap, v4.24.7
platformio-ide, v1.3.0
platformio-ide-terminal, v2.1.0
pull-requests, v0.0.23
python-indent, v0.4.3
python-isort, v0.0.7
python-jedi, v0.3.7
python-tools, v0.6.8
python-yapf, v0.11.0
slack-chat, v3.4.2
sync-settings, v0.7.2
tool-bar, v1.0.0
vagrant, v0.1.0

# Dev
No dev packages
```

**Comment by demux** [comment]
Has anyone solved this?
