### ISSUE TITLE
Uncaught TypeError: Cannot read property 'forEach' of null

### ISSUE THREAD

**Issue by qingfeng** [philschatz/atom-pull-requests#27]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**Thrown From**: [pull-requests](https://github.com/philschatz/atom-pull-requests) package, v0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'forEach' of null

```
At /Users/qingfeng/Dropbox/atom_config/packages/pull-requests/lib/tree-view-decorator.coffee:66

TypeError: Cannot read property 'forEach' of null
    at TreeViewDecorator.module.exports.TreeViewDecorator.updateTreeView (/Users/qingfeng/Dropbox/atom_config/packages/pull-requests/lib/tree-view-decorator.coffee:66:15)
    at /Users/qingfeng/Dropbox/atom_config/packages/pull-requests/lib/tree-view-decorator.coffee:43:41
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Object.<anonymous> (/Users/qingfeng/Dropbox/atom_config/packages/pull-requests/lib/gh-client.coffee:190:18)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3256:33)
    at fire (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3099:30)
    at Object.fireWith [as resolveWith] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3211:7)
    at Object.deferred.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3301:34)
    at fire (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3099:30)
    at Object.fireWith [as resolveWith] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3211:7)
    at Object.deferred.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3301:34)
    at fire (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3099:30)
    at Object.fireWith [as resolveWith] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3211:7)
    at Object.deferred.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3301:34)
    at fire (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3099:30)
    at Object.fireWith [as resolveWith] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3211:7)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3263:41)
    at fire (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3099:30)
    at Object.fireWith [as resolveWith] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3211:7)
    at Object.deferred.(anonymous function) [as resolve] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3301:34)
    at resolve (/Users/qingfeng/Dropbox/atom_config/packages/pull-requests/node_modules/octokat/dist/node/helper-promise.js:51:28)
    at cb (/Users/qingfeng/Dropbox/atom_config/packages/pull-requests/node_modules/octokat/dist/node/helper-promise.js:120:20)
    at /Users/qingfeng/Dropbox/atom_config/packages/pull-requests/node_modules/octokat/dist/node/octokat.js:82:18
    at /Users/qingfeng/Dropbox/atom_config/packages/pull-requests/node_modules/octokat/dist/node/request.js:195:22
    at XMLHttpRequest.xhr.onreadystatechange (/Users/qingfeng/Dropbox/atom_config/packages/pull-requests/node_modules/octokat/dist/node/request.js:43:18)
```

### Commands

```
     -5:27.7.0 tree-view:toggle (div.panels-item)
     -5:23.6.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.pronama-chan.theme-an-old-hope-syntax.theme-one-dark-ui)
     -5:17.4.0 core:close (div.deprecation-cop.pane-item.native-key-bindings)
     -5:16 settings-view:open (input.hidden-input)
     -3:41.8.0 core:paste (input.hidden-input)
     -3:41.2.0 core:confirm (input.hidden-input)
     -1:45.2.0 core:select-all (input.hidden-input)
     -1:45 core:paste (input.hidden-input)
  2x -1:44.3.0 core:confirm (input.hidden-input)
     -1:31.6.0 core:select-all (input.hidden-input)
  2x -1:31.3.0 core:copy (input.hidden-input)
     -0:26.5.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:24.9.0 editor:consolidate-selections (input.hidden-input)
     -0:24.9.0 core:cancel (input.hidden-input)
     -0:07.5.0 pane:show-next-item (input.hidden-input)
     -0:07.2.0 pane:show-previous-item (div.package-detail.panels-item)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "pep8",
      "task-list",
      "tester-go",
      "autocomplete-go",
      "linter-eslint",
      "activate-power-mode",
      "linter-jscs",
      "go-debug",
      "go-plus",
      "react",
      "go-signature-statusbar",
      "uniq-background"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "an-old-hope-syntax"
    ]
  },
  "pull-requests": {
    "githubAuthorizationToken": "5bd5f805848bf238fdd1a3bc7cc9da441adfef37"
  }
}
```

### Installed Packages

```coffee
# User
achievements, v0.9.0 (active)
activate-power-mode, v1.2.0 (inactive)
an-old-hope-syntax, v1.0.1 (active)
atom-fuzzy-grep, v0.15.0 (inactive)
atom-pronama-chan, v1.0.1 (active)
autocomplete-go, v1.3.0 (inactive)
batman-syntax, v1.1.0 (inactive)
bottom-dock, v0.4.4 (active)
cake-syntax, v1.0.2 (inactive)
colorful-cursor, v0.3.1 (active)
counter, v0.3.5 (active)
dash, v1.7.0 (inactive)
django-templates, v0.5.0 (active)
editor-stats, v0.17.0 (active)
editorconfig, v2.2.0 (active)
environment, v1.3.1 (active)
file-icons, v2.0.14 (active)
fruits, v6.0.0 (inactive)
genesis-ui, v0.5.0 (inactive)
gist-it, v0.9.2 (active)
git-plus, v7.2.0 (active)
git-time-machine, v1.5.4 (inactive)
go-debug, v1.0.4 (inactive)
go-plus, v5.1.1 (inactive)
go-signature-statusbar, v1.2.0 (inactive)
idiomatic-dark-syntax, v0.1.3 (inactive)
language-asciidoc, v1.7.0 (active)
language-django, v0.1.1 (active)
linter, v1.11.21 (active)
linter-eslint, v8.1.0 (inactive)
linter-flake8, v2.1.4 (inactive)
linter-jscs, v4.1.1 (inactive)
local-history, v4.0.1 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.26.8 (active)
minimap-cursorline, v0.2.0 (active)
minimap-git-diff, v4.3.1 (active)
minimap-linter, v1.6.0 (active)
monokai, v0.20.0 (inactive)
news-line, v0.2.0 (active)
nyancat, v0.12.0 (active)
pigments, v0.39.0 (active)
process-palette, v0.11.0 (active)
pull-requests, v0.1.0 (active)
react, v0.16.2 (inactive)
tester-go, v2.0.2 (inactive)
todo-manager, v0.2.10 (active)
toggl, v0.6.0 (inactive)
travis-ci-status, v1.3.0 (active)
uniq-background, v0.3.0 (inactive)
wakatime, v6.0.12 (active)
zentabs, v0.8.8 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
metrics, v1.1.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by tbehling** [comment]
Hi there @qingfeng, it appears you've pasted in your Personal Access Token in the JSON above; I would like to suggest you consider regenerating that token at https://github.com/settings/tokens .
