### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by paradox460** [philschatz/atom-pull-requests#6]
**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [pull-requests](https://github.com/philschatz/atom-pull-requests) package, v0.0.16

### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:829

TypeError: Cannot read property '0' of null
    at getRepoNameWithOwner (/Users/jeffsandberg/.atom/packages/pull-requests/lib/gh-client.coffee:16:77)
    at GitHubClient.module.exports.GitHubClient.updateRepoBranch (/Users/jeffsandberg/.atom/packages/pull-requests/lib/gh-client.coffee:119:29)
    at /Users/jeffsandberg/.atom/packages/pull-requests/lib/gh-client.coffee:54:53
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1067:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:602:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:534:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:517:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:648:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  4x -1:12.2.0 blur (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
  2x -0:32.2.0 editor:delete-line (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:29.4.0 core:save (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
  4x -0:29.2.0 blur (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
  9x -0:13.2.0 editor:delete-line (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:10.5.0 core:save (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
  3x -0:08.6.0 blur (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:06.4.0 markdown-writer:insert-new-line (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:06.4.0 editor:newline (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:06.0 markdown-writer:insert-new-line (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:06.0 editor:newline (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:02.6.0 markdown-writer:insert-new-line (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:02.6.0 editor:newline (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:00.6.0 markdown-writer:insert-new-line (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:00.6.0 editor:newline (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:00.0 core:save (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "save-session",
      "emacs-flow",
      "autocomplete",
      "feedback",
      "deprecation-cop",
      "ruby-string-interpolation"
    ],
    "excludeVcsIgnoredPaths": false,
    "packagesWithKeymapsDisabled": [
      "highlight-line",
      "whitespace",
      "notifications",
      "string-looper"
    ],
    "themes": [
      "tomorrow-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "pull-requests": {
    "githubAuthorizationToken": "97ede14f021d34e99c4b3d2a78bd2714235f5c8f"
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by philschatz** [comment]
Thanks for reporting! `0.0.18` should fix this issue. Please close this if it resolves your issue.

related to #5
