### ISSUE TITLE
Failed to activate the pull-requests package

### ISSUE THREAD

**Issue by molovo** [philschatz/atom-pull-requests#9]
[Enter steps to reproduce below:]

1. Install package

**Atom Version**: 1.7.0-beta0
**System**: Mac OS X 10.11.3
**Thrown From**: [pull-requests](https://github.com/philschatz/atom-pull-requests) package, v0.0.19

### Stack Trace

Failed to activate the pull-requests package

```
At service.register is not a function

TypeError: service.register is not a function
    at Object.module.exports.setLinterIndieService (/Users/molovo/.zprezto/runcoms/.atom/packages/php-integrator-linter/lib/Main.coffee:108:43)
    at Provider.module.exports.Provider.provide (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:352:71)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:186:16)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:535:21)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:448:29
    at exit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at ChildProcess.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -0:57.2.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
  2x -0:54.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-phpcs",
      "language-gfm",
      "formatter",
      "formatter-coffeescript"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "node_modules",
      "._*",
      "Thumbs.db",
      ".tags*"
    ],
    "packagesWithKeymapsDisabled": [
      "git-projects",
      "color-picker"
    ],
    "projectHome": "/usr/local/var/www",
    "themes": [
      "spacegray-dark-neue-ui",
      "base16-ocean-dark-spacegray"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
aligner, v0.19.1
aligner-css, v1.2.0
aligner-php, v1.0.0
aligner-ruby, v1.4.0
aligner-scss, v1.1.0
atom-alignment, v0.12.1
atom-jade, v0.3.0
autocomplete-modules, v1.4.1
autocomplete-paths, v1.0.2
base16-ocean-dark-spacegray, v0.12.0
battery-status, v0.11.0
codeception-snippets, v0.1.0
docblockr, v0.7.3
emmet, v2.4.2
file-icons, v1.6.18
imdone-atom, v1.3.29
imdone-atom-github, v0.1.9
language-markdown, v0.11.0
line-count-status, v0.0.3
linter, v1.11.4
linter-alex, v2.0.0
linter-coffee-variables, v0.5.0
linter-coffeelint, v1.1.2
linter-htmlhint, v1.1.0
linter-jade, v0.3.2
linter-jsonlint, v1.2.1
linter-just-say-no, v0.6.1
linter-package-json-validator, v1.0.1
linter-phpmd, v1.4.1
linter-proselint, v3.0.0
linter-sass-lint, v1.2.0
linter-write-good, v0.6.1
minimap, v4.21.0
minimap-find-and-replace, v4.5.0
minimap-git-diff, v4.2.0
minimap-linter, v1.1.1
minimap-pigments, v0.2.0
minimap-selection, v4.4.0
minimap-split-diff, v0.3.0
package-cop, v0.2.10
package-sync, v1.0.0
php-cs-fixer, v2.5.6
php-getters-setters, v0.5.5
php-integrator-annotations, v0.3.2
php-integrator-autocomplete-plus, v0.6.0
php-integrator-base, v0.7.2
php-integrator-call-tips, v0.2.2
php-integrator-linter, v0.2.1
php-integrator-navigation, v0.6.1
php-integrator-refactoring, v0.4.0
php-integrator-tooltips, v0.5.0
pigments, v0.24.5
project-manager, v2.7.6
pull-requests, v0.0.19
smart-tags, v0.1.0
spacegray-dark-neue-ui, v1.4.0
synced-sidebar, v0.4.3
travis-ci-status, v1.0.0
tree-view-git-branch, v0.0.6
tree-view-git-status, v0.2.3

# Dev
No dev packages
```

**Comment by philschatz** [comment]
Thanks for reporting! From the stack trace it looks like the exception came from `php-integrator-linter@v0.2.1`.

When I install, I get the same thing:

![image](https://cloud.githubusercontent.com/assets/253202/14228674/3c363cb8-f8ea-11e5-9e13-dc73284a39d1.png)

Does `php-integrator-linter` still work for you when you uninstalled `atom-pull-requests`?

But it did uncover a small error 83ee7ee which should be fixed in `0.0.21`.

**Comment by molovo** [comment]
Yeah `php-integrator-linter` started working after uninstalling `atom-pull-requests`.

**Comment by philschatz** [comment]
Thank you for confirming! There was a typo in 8e279b6a8fcc29d8296e12643c91392fd54eb849 that caused the problem but `0.0.22` should now work.

**Comment by molovo** [comment]
Cheers, I'll give it a go

**Comment by philschatz** [comment]
Any luck?

**Comment by molovo** [comment]
Forgot about this issue. The commit above did resolve the issue
